name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output: reti_interpreter-linux
          - os: macos-latest
            output: reti_interpreter-macos
          - os: windows-latest
            output: reti_interpreter-windows.exe

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Set up environment
      if: matrix.os == 'macos-latest'
      run: brew install gcc

    - name: Set up environment
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw
        dir "C:\ProgramData\mingw64\mingw64\bin"
        echo "C:\ProgramData\mingw64\mingw64\bin" >> $GITHUB_PATH
      shell: bash

    - name: Build with Make
      run: |
        make
        mv ./bin/reti_interpreter_main ./bin/${{ matrix.output }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output }}
        path: ./bin/${{ matrix.output }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./reti_interpreter-linux/reti_interpreter-linux
          ./reti_interpreter-macos/reti_interpreter-macos
          ./reti_interpreter-windows/reti_interpreter-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
